/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://uhuagis2uvgsdjpxzpoiec324i.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-k4o5l3rydvbjro2tcxr5kyrd7q",
    "aws_cognito_identity_pool_id": "us-east-1:c932cd94-5060-483e-9e6d-b0082cc1e557",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_t105InpOE",
    "aws_user_pools_web_client_id": "pb9ads4augpp6nar5ggit3qbq",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "PREFERRED_USERNAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "laundryblocks-storage-1bba9373162019-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
